#!/usr/bin/python3
import subprocess
import sys

import fire


def sh(command, capture=False, **kwargs):
    if capture: kwargs.update(stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if not sys.stdin.isatty(): kwargs.update(stdin=sys.stdin)
    process = subprocess.Popen(command, shell=True, **kwargs)
    (stdout, stderr) = process.communicate()
    if process.returncode: exit((stderr or b'').decode('utf-8'))
    return (stdout or b'').decode('utf-8').strip()


if __name__ == '__main__':
    fire.Fire()
