#!/usr/bin/python3
import subprocess

import fire


def sh(command, capture=False):
    kwargs = {}
    if capture:
        kwargs.update(stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    process = subprocess.Popen(command, shell=True, **kwargs)
    (stdout, stderr) = process.communicate()
    if process.returncode:
        print((stderr or b'').decode('utf-8'))
        exit(process.returncode)
    return (stdout or b'').decode('utf-8').strip()


if __name__ == '__main__':
    fire.Fire()
