version: '3.2'
services:
  app:
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /sys/kernel/debug:/sys/kernel/debug
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/X11:/usr/share/X11:ro
      - ./:/opt/app
    environment:
      DISPLAY: unix$DISPLAY
    privileged: true
    network_mode: host
    pid: host
    # command: ./app
    cap_add:
      - ALL

      - AUDIT_CONTROL
      - AUDIT_WRITE
      - BLOCK_SUSPEND
      - CHOWN
      - DAC_OVERRIDE
      - DAC_READ_SEARCH
      - FOWNER
      - FSETID
      - IPC_LOCK
      - IPC_OWNER
      - KILL
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - MKNOD
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_CHROOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - SYSLOG
      - WAKE_ALARM
